### ISSUE TITLE
Are you interested in having pull requests?

### ISSUE THREAD

**Issue by ovgray** [mirovskyi/stripe-bundle#1]
I found your new bundle just as I was starting to work on integrating stripe webhooks into a project I am working on. You have done a lot of good work. Your code  is a great foundation for my work.

I have found some typos and errors in the code, for which I can provide pull requests.

I would suggest pushing the livemode and webhooks methods down from StripeModelInterface into the model Interfaces, in part because the items you are modelling do not all have a livemode property. More importantly, there is no reason to require the user to include those properties in the models that the user wants the webhooks to create or update. I can provide a pull request for that, as well as one for an update of the stripe-php dependency to the 3.\* version 

Would you like to see these?

**Comment by mirovskyi** [comment]
Sorry, I just seen your message.
I fixed some bugs, but this bundle is still raw.
It will be great if you create pull request.
